---
include:
  - board: nice_nano_v2
    shield: redox_left
  - board: nice_nano_v2
    shield: redox_right

  - board: nice_nano_v2
    shield: reviung41

  # - board: nice_nano_v2
  #   shield: nyx_left
  # - board: nice_nano_v2
  #   shield: nyx_right

  # - board: nice_nano_v2
  #   shield: kyria_rev2_left
  # - board: nice_nano_v2
  #   shield: kyria_rev2_right

  # - board: nice_nano_v2
  #   shield: corne_left
  # - board: nice_nano_v2
  #   shield: corne_right

  - board: nice_nano
    shield: taira_left
  - board: nice_nano
    shield: taira_right

  - board: seeeduino_xiao
    shield: revxlp
  - board: seeeduino_xiao_ble
    shield: revxlp

  - board: nice_nano_v2
    shield: eternal_keypad_lefty

  # - board: seeeduino_xiao_ble
  #   shield: totem_left
  # - board: seeeduino_xiao_ble
  #   shield: totem_right

  - board: nice_nano_v2
    shield: settings_reset
