manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      ## use urobs fork until mouse support is merged
      # remote: zmkfirmware
      remote: urob 
      revision: main
      import: app/west.yml
  self:
    path: config
