on: [push, pull_request, workflow_dispatch]

jobs:
  build-mykeeb:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: config/mykeeb.build.yaml
  build-taira:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: config/taira.build.yaml
  build-eternal_keypad:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: config/eternal_keypad.build.yaml
  build-revxlp:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: config/revxlp.build.yaml
  build-redox:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: config/redox.build.yaml
  build-totem:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: config/totem.build.yaml
  build-settings_reset:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: config/settings_reset.build.yaml
